language: swift
osx_image: xcode10.2

install:
- brew install swiftlint

script:
- xcodebuild -workspace Example/Guppy.xcworkspace -scheme Example -sdk iphonesimulator build test
- swiftlint --strict
