name: Swift CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Test
      run: |
        xcodebuild -scheme Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' build test
        swiftlint --strict
        bash <(curl -s https://codecov.io/bash)
